fix --min_link_speed

diff --git a/master_scripts/S20outbreak/outbreak b/master_scripts/S20outbreak/outbreak
--- a/master_scripts/S20outbreak/outbreak
+++ b/master_scripts/S20outbreak/outbreak
@@ -912,16 +912,35 @@ get_pingable_clients() {
     make -s -f ${ping_mk} -j last_octets="${last_octets}"
 }
 
+check_master_speed() {
+    interface=$(ip -o -4 address | grep 10.0.3 | awk '{ print $2 }')
+    if [ "${interface}" = "" ]; then
+        echo "could not find interface for 10.0.3.x" 1>&2
+        exit 1
+    fi
+    speed=$(cat /sys/class/net/${interface}/speed)
+    if [ "${interface}" = "" ]; then
+        echo "could not get the speed of interface ${interface}" 1>&2
+        exit 1
+    fi
+    if [ ${speed} -lt ${min_link_speed} ] ; then
+        echo "speed of interface ${interface} is slow (= ${speed} < --min_link_speed = ${min_link_speed})" 1>&2
+        echo "to proceed with it, specify --min_link_speed ${speed}" 1>&2
+        exit 1
+    fi
+}
+
+apply_min_link_speed() {
+    check_master_speed
+    echo "checking the link speed of clients (use e.g., --min_link_speed 1000 to choose only clients whose link speed are >= 1000)"
+    gxpc -G ${src_gupid} e "echo \$(hostname -I) : \$(cat /sys/class/net/enp*/speed)" | sort
+    gxpc -G ${src_gupid} e "[ \$(cat /sys/class/net/enp*/speed) -lt ${min_link_speed} ]"
+    gxpc smask -
+}
+
 #
 # clients, depending on it is a production run or local test
 #
-
-apply_min_link_speed() {
-    echo "checking the link speed of clients (use e.g., --min_link_speed 1000 to choose only clients whose link speed are >= 1000)"
-    gxpc -G ${src_gupid} e "echo \$(hostname -I) : \$(cat /sys/class/net/enp*/speed)" | sort
-    gxpc -G ${src_gupid} e "[ \$(cat /sys/class/net/enp*/speed) -ge ${min_link_speed} ]"
-    gxpc smask
-}
 
 #
 # explore clients. make a temporary directory under
